framework:
    secret: '%env(APP_SECRET)%'
    form: ~
    csrf_protection: ~
    validation:
        mapping:
            paths: 
                - '%kernel.project_dir%/config/validation.xml'
    trusted_hosts: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
        cookie_secure: auto
    fragments: ~
    http_method_override: true
    #assets:
    #    version: v1

