version: '3.3'
services:
    database:
        build: config/docker/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
    php:
        build: config/docker/php-fpm
        volumes:
            - ./:/user/progetto:delegated
            - $HOME/.bashrc:/user/.bashrc:delegated
            - $HOME/.composer:/user/.composer:delegated
            - $HOME/.gitignore:/user/.gitignore:delegated
            - $HOME/.vimrc:/user/.vimrc:delegated
        working_dir: /user/progetto
        ports:
            - 9000:9000
        links:
            - database
        environment:
            - PATH=./bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - COLUMNS=190
            - LINES=42
            - APP_ENV=dev
            - APP_DEBUG=1
            - APP_DATABASE_URL=mysql://root:root@database/symfony?charset=utf8mb4
            - APP_TEST_DATABASE_URL=mysql://root:root@database/symfony_test?charset=utf8mb4
            - APP_MAILER_URL=null://127.0.0.1
            - APP_SECRET=ThisIsNotReallySecretButOK
            - APP_DOMAIN=progetto.local
    nginx:
        build: config/docker/nginx
        ports:
            - 8080:80
        links:
            - php
        volumes:
            - ./:/user/progetto:delegated
    phpunit:
        build: config/docker/php-cli
        volumes:
            - ./:/user/progetto
        working_dir: /user/progetto
        tty: true
        links:
            - database
        environment:
            - PATH=./bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - COLUMNS=190
            - LINES=42
            - APP_ENV=test
            - APP_DEBUG=1
            - APP_TEST_DATABASE_URL=mysql://root:root@database/symfony_test?charset=utf8mb4
            - APP_MAILER_URL=null://127.0.0.1
            - APP_SECRET=ThisIsNotReallySecretButOK
            - APP_DOMAIN=progetto.local:8080

