parameters:
    locale: it
    domain: '%env(APP_DOMAIN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '%kernel.project_dir%/src/*'
        exclude: '%kernel.project_dir%/src/{DataFixtures,Dominio,Kernel.php}'

    App\Controller\:
        resource: '%kernel.project_dir%/src/Controller'
        tags: ['controller.service_arguments']

    Dominio\Progetto\Handler\:
        resource: '%kernel.project_dir%/src/Dominio/Progetto/Handler'
        exclude: '%kernel.project_dir%/src/Dominio/Progetto/Handler/*/Abstract*'
        public: true
        tags:
            - { name: 'command_handler', register_public_methods: true }

    # alias
    Dominio\Progetto\Encoder\PasswordEncoderInterface: '@App\Encoder\PasswordEncoder'
    Dominio\Progetto\Mailer\MailerInterface: '@App\Mailer\Mailer'
    Dominio\Progetto\Repository\UtenteRepositoryInterface: '@App\Repository\UtenteRepository'
    SimpleBus\Message\Bus\MessageBus: '@command_bus'
