services:
    App\DataFixtures\:
        resource: '%kernel.project_dir%/src/DataFixtures/*'
        autowire: true
        autoconfigure: true
        public: false

    Fixtures\:
        resource: '../fixtures/*'
        tags: ['doctrine.fixture.orm']

    test.userprovider:
        alias: security.user.provider.concrete.progetto
        public: true

